# This file describes the firmwares that are built by the GitHub Actions CI.
#  - all supported keebs have a dedicated firmware implementing `selenium.keymap`
#  - `__tester_*` artifacts are dummy keebs that just ensure options can be built

include:

  ###
  # ProMicro-Based Keyboards
  #
  # These keebs consist in two parts:
  #  - a shield = the keyboard itself
  #  - a board = the micro-controller unit (MCU), which can be:
  #    - nice_nano@2 (nice!nano v2)
  #    - sparkfun_pro_micro_rp2040
  #    - xiao_ble
  #    - ... and many others
  #
  # => make sure the `board` field matches the MCU on your keyboard
  ##

  # Quacken Zero + SparkFun RP2040
  - board: sparkfun_pro_micro_rp2040//zmk
    shield: quacken_zero
    artifact-name: quacken_zero
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y

  # Totem + XIAO BLE
  - board: xiao_ble//zmk
    shield: totem_left
    artifact-name: totem_left
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y
  - board: xiao_ble//zmk
    shield: totem_right
    artifact-name: totem_right
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y

  # Corne + nice!nano v2
  - board: nice_nano@2//zmk
    shield: corne_left
    artifact-name: corne_left
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano@2//zmk
    shield: corne_right
    artifact-name: corne_right
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y

  # Sweep + SparkFun RP2040
  - board: sparkfun_pro_micro_rp2040//zmk
    shield: cradio_left
    artifact-name: sweep_left
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y
  - board: sparkfun_pro_micro_rp2040//zmk
    shield: cradio_right
    artifact-name: sweep_right
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y


  ###
  # Standalone Keyboards (onboard MCU)
  ##

  # Quacken Flex (RP2040)
  - board: quacken_flex/rp2040
    artifact-name: quacken_flex
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y

  # Ferris (STM32F072)
  # Note: not enough memory for ZMK Studio
  - board: ferris//zmk
    artifact-name: ferris

  # Glove80
  - board: glove80_lh
    artifact-name: glove80_left
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y
  - board: glove80_rh
    artifact-name: glove80_right
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y


  ###
  # Keymap Checks: dummy keeb + command-line options
  ##

  # Pro Micro RP2040, default config
  - board: sparkfun_pro_micro_rp2040//zmk
    shield: corne_left
    artifact-name: __tester_rp2040
    cmake-args: -DDTS_EXTRA_CPPFLAGS="-DCI_IGNORE_USER_SETTINGS"

  # Pro Micro RP2040, Qwerty + Vim + hrm_shift
  - board: sparkfun_pro_micro_rp2040//zmk
    shield: corne_left
    artifact-name: __tester_rp2040_qwerty_vim_shift
    cmake-args: -DDTS_EXTRA_CPPFLAGS="-DCI_IGNORE_USER_SETTINGS;-DVIM_NAVIGATION;-DHRM_SHIFT"

  # Pro Micro RP2040, Azerty + thumb-taps
  - board: sparkfun_pro_micro_rp2040//zmk
    shield: corne_left
    artifact-name: __tester_rp2040_azerty_tt
    cmake-args: -DDTS_EXTRA_CPPFLAGS="-DCI_IGNORE_USER_SETTINGS;-DKB_LAYOUT_AZERTY;-DHT_THUMB_TAPS"

  # Pro Micro RP2040, Ergol + Hummingbird
  - board: sparkfun_pro_micro_rp2040//zmk
    shield: corne_left
    artifact-name: __tester_rp2040_ergol_hummingbird
    cmake-args: -DDTS_EXTRA_CPPFLAGS="-DCI_IGNORE_USER_SETTINGS;-DKB_LAYOUT_ERGOL;-DHUMMINGBIRD"
