on: [push, pull_request]

jobs:
  ci:
    name: "ci: Build test firmwares with various configuration options"
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      archive_name: firmware-tester-selenium
      build_matrix_path: ci.yaml
