on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      archive_name: firmware-selenium
  ci:
    name: "ci: Build test firmwares with various configuration options"
    if: github.event_name == 'workflow_dispatch' || vars.RUN_CI == 1
    # Only run `ci` after `build` as `build-user-config.yml` does not seem
    # to support concurrent runs
    needs: build
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      archive_name: firmware-tester-selenium
      build_matrix_path: tests.yaml
